.gitignore
cmd/nettop/main.go
go.mod
pkg/analyzer/scan.go
pkg/common/params.go
pkg/common/types.go
pkg/controller/connections.go
pkg/controller/controller_test.go
pkg/controller/engine.go
pkg/controller/synth_netpols.go
pkg/controller/utils.go
tests/onlineboutique/expected_dirscan_output.json
tests/onlineboutique/expected_netpol_output.json
tests/onlineboutique/expected_output.json

Also, fixing a bug in parsing multi-document yamls.
Also, fixing a crash when the top-level dir contains yamls

A flag to output synthesized netpols instead of a connection list

---

.github/workflows/make-release.yaml

publish module to pkg.go.dev in release workflow

---

pkg/analyzer/scan.go
pkg/common/types.go
pkg/controller/engine.go
tests/onlineboutique/expected_dirscan_output.json
tests/onlineboutique/expected_output.json
tests/onlineboutique/kubernetes-manifests.yaml

issue #40: support for ConfigMapKeyRef

---

pkg/analyzer/scan.go
pkg/controller/connections.go
pkg/controller/controller_test.go
pkg/controller/synth_netpols.go
tests/k8s_wordpress_example/expected_netpol_output.json
tests/k8s_wordpress_example/mysql-deployment.yaml
tests/k8s_wordpress_example/wordpress-deployment.yaml

Also handle environment value with no port specified
Also, a new test
Fixes #49

handle svc with no target-port

---

.github/workflows/codeql-analysis.yml
.github/workflows/go-build.yml
.github/workflows/golangci-lint.yml
.github/workflows/make-release.yaml
Dockerfile

Handles some of the tasks in #53

Set workflow permissions + hash pinning

---

pkg/common/params.go
pkg/common/types.go
pkg/controller/controller_test.go
pkg/controller/engine.go
pkg/controller/policies_synthesizer.go
tests/onlineboutique/expected_dirscan_output.json
tests/onlineboutique/expected_output.json

Remove git switches and data members

---

.github/workflows/go-build.yml
Makefile
cmd/nettop/main.go
cmd/nettop/main_test.go
cmd/nettop/parse_args.go
pkg/common/types.go
pkg/controller/connections.go
pkg/controller/controller_test.go
pkg/controller/engine.go
pkg/controller/policies_synthesizer.go
pkg/controller/synth_netpols.go

Also, move non-API code to cmd/nettop

Export api for extracting connections

---

.github/workflows/make-release.yaml
Dockerfile

Pushing a version tag triggers release

---

cmd/nettop/main.go
cmd/nettop/main_test.go
cmd/nettop/parse_args.go
pkg/controller/logger.go

Control verbosity level

---

.github/workflows/golangci-lint.yml

fixed golangci_lint version

---

.github/workflows/go-build.yml
.github/workflows/golangci-lint.yml
.github/workflows/make-release.yaml
Dockerfile
README.md
go.mod
go.sum

Bump to go 1.18

---

pkg/controller/controller_test.go
pkg/controller/engine.go
pkg/controller/example_test.go
pkg/controller/policies_synthesizer.go
pkg/controller/synth_netpols.go
tests/bookinfo/expected_netpol_output.json
tests/k8s_guestbook/expected_netpol_output.json
tests/k8s_wordpress_example/expected_netpol_output.json
tests/onlineboutique/expected_netpol_interface_output.json
tests/onlineboutique/expected_netpol_output.json
tests/onlineboutique/expected_netpol_output.yaml
tests/sockshop/expected_netpol_output.json

issue #113: default-deny netpol for each namespace

---

pkg/controller/example_test.go
pkg/controller/synth_netpols.go
tests/bookinfo/expected_netpol_output.json
tests/k8s_wordpress_example/expected_netpol_output.json
tests/onlineboutique/expected_netpol_interface_output.json
tests/onlineboutique/expected_netpol_output.json
tests/onlineboutique/expected_netpol_output.yaml

netpol name cannot end with -

---

pkg/common/types.go
pkg/controller/controller_test.go
pkg/controller/engine.go
pkg/controller/policies_synthesizer.go
pkg/controller/utils.go
pkg/controller/utils_test.go

Fixes #82 
Also in this PR:
* Making `extractConnections` a member function of `PoliciesSynthesizer`
* Removing unused consts

User provided dir-scanning function

---

.github/dependabot.yml

Dependabot to update Docker base image

---

pkg/analyzer/scan.go
pkg/common/types.go
pkg/controller/resource_finder.go
tests/onlineboutique/expected_dirscan_output.json
tests/onlineboutique/expected_output.json
tests/onlineboutique/expected_output.yaml

Also in this PR: properly extracting the filename of the manifest

Not storing selectors for workloads

---

pkg/controller/example_test.go
pkg/controller/synth_netpols.go
tests/bookinfo/expected_netpol_output.json
tests/k8s_guestbook/expected_netpol_output.json
tests/k8s_wordpress_example/expected_netpol_output.json
tests/onlineboutique/expected_netpol_interface_output.json
tests/onlineboutique/expected_netpol_output.json
tests/onlineboutique/expected_netpol_output.yaml
tests/sockshop/expected_netpol_output.json

Limiting added DNS rule to in-cluster traffic

---

pkg/controller/controller_test.go
pkg/controller/error_types.go
pkg/controller/logger.go
pkg/controller/policies_synthesizer.go
pkg/controller/resource_finder_test.go

Typed errors

---

CONTRIBUTING.md
Dockerfile
README.md

Also updating golang image to the latest release

Update docs to reflect changes to Makefile

---

README.md

Updating README with Ingress, Routes, extracting network addrs from cmd and args.

---

pkg/analyzer/scan.go
tests/k8s_guestbook/redis-leader-deployment.yaml

Fix a bug in setting labels for ReplicaSet pods

---

go.mod
go.sum
pkg/analyzer/info_to_resource_test.go
pkg/analyzer/policies_synthesizer_test.go
pkg/analyzer/resource_accumulator.go

update go.mod + fix imports from manifests pkg

update netpol-analyzer in go.mod to v1.1.0
